// <auto-generated />
namespace DialoguesDbStuff.Migrations
{
  using System.CodeDom.Compiler;
  using System.Data.Entity.Migrations.Infrastructure;
  using System.Resources;

  [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DialogueMessage_Controlled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DialogueMessage_Controlled));
        
        string IMigrationMetadata.Id
        {
            get { return "202108100236373_DialogueMessage_Controlled"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
